version:"2.0"
sevices:
  app:
    build: ./script/
    depends_on:
      db:
        condition: service_helthy
    links:
      - db
  db:
    image: postgres:latest
    ports: 
      - 5432:5432
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always